export const CONST_NOTIFICATION_STATUS = {
  SUCCESS: "success",
  FAILED: "failed",
  WARNING: "warning",
  ALERT: "alert",
};

export const CONST_NOTIFICATION_DURATION = {
  DEFAULT: 5000,
};

export const CONST_NOTIFICATION_CONTENTS = {
  SIGNUP_SUCCESS: {
    title: "set-85_success",
    text: "ncca-68_sign-up-success",
    status: CONST_NOTIFICATION_STATUS.SUCCESS,
    duration: CONST_NOTIFICATION_DURATION.DEFAULT,
    link: "",
  },
  SIGNUP_FAIL: {
    title: "wal-56_failed",
    text: "ncca-69_sign-up-failed",
    status: CONST_NOTIFICATION_STATUS.FAILED,
    duration: CONST_NOTIFICATION_DURATION.DEFAULT,
    link: "",
  },
  LOGIN_SUCCESS: {
    title: "set-85_success",
    text: "ncca-70_login-success",
    status: CONST_NOTIFICATION_STATUS.SUCCESS,
    duration: CONST_NOTIFICATION_DURATION.DEFAULT,
    link: "",
  },
  LOGIN_FAIL: {
    title: "wal-56_failed",
    text: "ncca-71_login_failed",
    status: CONST_NOTIFICATION_STATUS.FAILED,
    duration: CONST_NOTIFICATION_DURATION.DEFAULT,
    link: "",
  },
  GAME_REFRESH_SUCCESS: {
    title: "set-85_success",
    text: "ga-41_game-list-updated",
    status: CONST_NOTIFICATION_STATUS.SUCCESS,
    duration: CONST_NOTIFICATION_DURATION.DEFAULT,
    link: "",
  },
  GAME_REFRESH_FAIL: {
    title: "wal-56_failed",
    text: "ga-42_game-list-udpating-failed",
    status: CONST_NOTIFICATION_STATUS.FAILED,
    duration: CONST_NOTIFICATION_DURATION.DEFAULT,
    link: "",
  },
  DOWNLOAD_START: {
    title: "set-85_success",
    text: "alt-28_download-start",
    status: CONST_NOTIFICATION_STATUS.SUCCESS,
    duration: CONST_NOTIFICATION_DURATION.DEFAULT,
    link: "",
  },
  DOWNLOAD_END: {
    title: "set-85_success",
    text: "alt-7_download-finish",
    status: CONST_NOTIFICATION_STATUS.SUCCESS,
    duration: CONST_NOTIFICATION_DURATION.DEFAULT,
    link: "",
  },
  DOWNLOAD_FAIL: {
    title: "alt-39_download-failed",
    text: "alt-39_download-failed",
    status: CONST_NOTIFICATION_STATUS.FAILED,
    duration: CONST_NOTIFICATION_DURATION.DEFAULT,
    link: "",
  },
  INTERNET_ERROR: {
    title: "alt-26_internet-error",
    text: "alt-27_you-not-connected",
    status: CONST_NOTIFICATION_STATUS.FAILED,
    duration: CONST_NOTIFICATION_DURATION.DEFAULT,
    link: "",
  },
  PROFILE_UPDATE_SUCCESS: {
    title: "set-85_success",
    text: "set-99_profile-updated-successfully",
    status: CONST_NOTIFICATION_STATUS.SUCCESS,
    duration: CONST_NOTIFICATION_DURATION.DEFAULT,
    link: "",
  },
  PROFILE_UPDATE_FAIL: {
    title: "wal-56_failed",
    text: "set-100_profile-updated-failed",
    status: CONST_NOTIFICATION_STATUS.FAILED,
    duration: CONST_NOTIFICATION_DURATION.DEFAULT,
    link: "",
  },
  AVATAR_UPDATE_SUCCESS: {
    title: "alt-32_avatar-saved",
    text: "alt-33_avatar-saved-intro",
    status: CONST_NOTIFICATION_STATUS.SUCCESS,
    duration: CONST_NOTIFICATION_DURATION.DEFAULT,
    link: "",
  },
  AVATAR_UPDATE_FAIL: {
    title: "alt-34_avatar-notsaved",
    text: "alt-35_avatar-notsaved-intro",
    status: CONST_NOTIFICATION_STATUS.FAILED,
    duration: CONST_NOTIFICATION_DURATION.DEFAULT,
    link: "",
  },
  REMOVE_SUCCESS: {
    title: "set-85_success",
    text: "alt-30_game-removed",
    status: CONST_NOTIFICATION_STATUS.SUCCESS,
    duration: CONST_NOTIFICATION_DURATION.DEFAULT,
    link: "",
  },
  REMOVE_FAIL: {
    title: "wal-56_failed",
    text: "alt-40_game-remove-failed",
    status: CONST_NOTIFICATION_STATUS.FAILED,
    duration: CONST_NOTIFICATION_DURATION.DEFAULT,
    link: "",
  },
  VOTE_SUCCESS: {
    title: "set-85_success",
    text: "wal-48_successfully-voted",
    status: CONST_NOTIFICATION_STATUS.SUCCESS,
    duration: CONST_NOTIFICATION_DURATION.DEFAULT,
    link: "",
  },
  VOTE_FAIL: {
    title: "wal-56_failed",
    text: "wal-49_vote-failed",
    status: CONST_NOTIFICATION_STATUS.FAILED,
    duration: CONST_NOTIFICATION_DURATION.DEFAULT,
    link: "",
  },
  CHAIN_SELECT_SUCCESS: {
    title: "wal-83_connection-success",
    text: "wal-83_connection-success",
    status: CONST_NOTIFICATION_STATUS.SUCCESS,
    duration: CONST_NOTIFICATION_DURATION.DEFAULT,
    link: "",
  },
  CHAIN_SELECT_FAIL: {
    title: "wal-84_connection-failed",
    text: "wal-84_connection-failed",
    status: CONST_NOTIFICATION_STATUS.FAILED,
    duration: CONST_NOTIFICATION_DURATION.DEFAULT,
    link: "",
  },
  TX_SENT_SUCCESS: {
    title: "set-85_success",
    text: "wal-85_tx-success",
    status: CONST_NOTIFICATION_STATUS.SUCCESS,
    duration: CONST_NOTIFICATION_DURATION.DEFAULT,
    link: "",
  },
  TX_SENT_FAIL: {
    title: "wal-56_failed",
    text: "wal-86_tx-fail",
    status: CONST_NOTIFICATION_STATUS.FAILED,
    duration: CONST_NOTIFICATION_DURATION.DEFAULT,
    link: "",
  },
  ADDRESS_DUPLICATE: {
    title: "not-14_warning",
    text: "wal-87_address-duplicated",
    status: CONST_NOTIFICATION_STATUS.WARNING,
    duration: CONST_NOTIFICATION_DURATION.DEFAULT,
    link: "",
  },
};
